name: lint
on: [pull_request]
jobs:
  lint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          fail_on_error: true
          eslint_flags: "src/**/*.{js,ts,tsx}"
