name: test
on: [pull_request]
jobs:
  lint:
    name: runner / jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn test:ci
